Select * from customer;

--Q1. What is the total revenue generated by male vs. female customers?

Select gender ,sum(purchase_amount)
from customer
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

Select customer_id ,purchase_amount
from customer
where discount_applied = 'true' and purchase_amount >(select avg(purchase_amount) from customer) ;

--Q3. Which are the top 5 products with the highest average review rating?

Select item_purchased , round(avg(review_rating::numeric),2) as "Average Product Rating" 
from customer
group by item_purchased
order by avg(review_rating) DESC
LIMIT 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select * from customer;

select shipping_type , round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
Group by Shipping_type;


--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select * from customer;

select 
	sum(purchase_amount) as Total_Revenue , 
	round(avg(purchase_amount),2) as Average_Spend ,
	count(customer_id) as Total_Customer,
	subscription_status
from Customer
group by subscription_status
order by Total_Revenue , Average_Spend DESC;	

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased, round(100*(purchase_amount / sum(purchase_amount)),2) as Highest_perc_purchase
from customer
where discount_applied = 'true'
group by item_purchased,purchase_amount
order by Highest_perc_purchase DESC
LIMIT 5;

select item_purchased,
round(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.

select * from customer;

with customer_type as (
	select customer_id, previous_purchases,
		CASE 
			WHEN previous_purchases = 1 THEN 'New'
			WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
			ELSE 'Loyal'
		END AS customer_segment
	from customer
)

select customer_segment , count(*) as No_of_customer
from customer_type
group by customer_segment


--Q8. What are the top 3 most purchased products within each category? 

select * from customer;

with item_counts as(
	select category,item_purchased,count(customer_id) as total_orders,
	ROW_number() over(partition by category order by count(customer_id)DESC) as item_rank
	from customer
	group by category, item_purchased
)

select item_rank , category ,item_purchased,total_orders
from item_counts
where item_rank <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select * from customer; 

select subscription_status,count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--Q10. What is the revenue contribution of each age group? 
select * from customer;

select age_group,sum(purchase_amount) as Revenue
from customer
group by age_group
order by Revenue DESC;

